### ISSUE TITLE
Problems to obtain all results listed in paper

### ISSUE THREAD

**Issue by Wangjyddddddd** [boortel/SIFT-and-SURF-based-AD#2]
I run the ExtractFeatures.m, and got 'Warning - not enough feature points!' but still could run. I didn't get the results of table1 in your paper, and just get a part of results of table2.

**Comment by boortel** [comment]
Did you use the same dataset? Script DatasetFolder.py may require some setting to obtain dataset described in section 3.1.

Results from table 1 were obtained by the Matlab _Classification Learner Toolbox_ and the relevant scripts in this repository are generated from this toolbox. Results from table 2 should be achievable by running _ExtractFeatures.m_ - could you specify better which problems you had reached?

**Comment by boortel** [comment]
The warning message you reach (Warning - not enough feature points!) says, that the script was not able to get a suitable number of feature points due to low texture. It will run anyway and the missing feature points are gonna be filled with constant.

I work on a way, how to extract features in better manner.

**Comment by Wangjyddddddd** [comment]
Thank you so much sir!!  I use classification learner and get the results (a little different from yours but doesn't matter). I finally got the complete results about table2, but I got SIFT O-C SVM AUC 0.8, SIFT Semi SVM AUC 0.79557, SURF O-C SVDD AUC 0.56, SURF Semi SVDD AUC 0.6. But your results are 0.56, 0.6, 0.8, 0.79 which are symmetrical with mine, I'm a little confused.
Wish you a good day sir, maybe I have to many questions, lol.

**Comment by boortel** [comment]
Hi, I check it out and let you know - there might be a bug in the figure labels.

**Comment by boortel** [comment]
Hello, I checked the results once again and it is my fault - the SVM results are written in bad table columns. I fix it this week in the paper, repository should not be affected. Sorry for the troubles!

**Comment by Wangjyddddddd** [comment]
You are welcome, and thanks for helping me, wish you a good day sir!

**Comment by boortel** [comment]
Hello, the table in paper on arXiv is corrected - sorry for the inconvenience and thank you for notice! Feel free to ask any other questions.
